spring.application.name=notification-service


server.port= 8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false



spring.datasource.url=jdbc:mysql://localhost:3306/momstiffin?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example=TRACE


# Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=avinashsarwade3190@gmail.com
spring.mail.password=bwsi adzg ugbo qkqs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# MSG91
msg91.authkey=526593ACwJGzqnT6a2c4e86P1
msg91.sender=Dabbad
msg91.route=4
msg91.country=91

